# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/Fully_Connected_bram/Fully_Connected_bram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Fully_Connected_bram || ORIG_REF_NAME==Fully_Connected_bram} -quiet] -quiet

# XDC: c:/Users/long3/Desktop/CNN_Topic/CNN_Topic.gen/sources_1/ip/Fully_Connected_bram/Fully_Connected_bram_ooc.xdc
